// Generate OpenSCAD source for extruded profiles (round-trips into another open-source CAD tool).
const f = (n) => +n.toFixed(4);
const poly = (pts) => '[' + pts.map((p) => `[${f(p.x)},${f(p.y)}]`).join(',') + ']';

export function toOpenSCAD(profiles, { depth = 10, scale = 1 } = {}) {
  const lines = [
    '// Generated by DXF to 3D (https://github.com) - open in OpenSCAD',
    `depth = ${f(depth)};`,
    `scale_factor = ${f(scale)};`,
    '',
    'scale([scale_factor, scale_factor, 1])',
    'union() {',
  ];
  for (const p of profiles) {
    lines.push('  linear_extrude(height = depth)');
    if (p.holes.length) {
      lines.push(`    polygon(points = ${poly([p.outer, ...p.holes].flat())},`);
      let idx = 0;
      const paths = [p.outer, ...p.holes].map((l) => { const r = l.map((_, i) => idx + i); idx += l.length; return '[' + r.join(',') + ']'; });
      lines.push(`      paths = [${paths.join(',')}]);`);
    } else {
      lines.push(`    polygon(${poly(p.outer)});`);
    }
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}
